# Generated by Django 5.1.7 on 2025-04-05 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deffered_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=25, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('nin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
                ('duedate', models.DateField(default=datetime.datetime.now)),
                ('date_of_payment', models.DateField(default=datetime.datetime.now)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_agent', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
