# Generated by Django 5.1.7 on 2025-05-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsale',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='amount_due',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='balance',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='branch_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='customer_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='nin',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='quantity',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='salesagent',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='branch_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='branch_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
