# Generated by Django 5.1.7 on 2025-04-16 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0002_products_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deffered_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=25, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('nin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('amount_due', models.FloatField(blank=True, default=0, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('duedate', models.DateField(default=datetime.datetime.now)),
                ('date_of_payment', models.DateField(default=datetime.datetime.now)),
                ('branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('salesagent', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_dispatch', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_type', models.CharField(blank=True, max_length=50, null=True)),
                ('time_of_produce', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.FloatField(blank=True, default=0, null=True)),
                ('unit_cost', models.FloatField(blank=True, default=10, null=True)),
                ('unit_price', models.FloatField(blank=True, default=0, null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('issued_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, default=10, null=True)),
                ('amount_received', models.IntegerField(blank=True, default=10, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=50, null=True)),
                ('salesagent', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.FloatField(blank=True, default=10, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Deffered_payments',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
