# Generated by Django 5.1.7 on 2025-04-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0003_deffered_payment_product_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='total_quantity',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='issued_to',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='product_name',
            new_name='product',
        ),
    ]
