# Generated by Django 5.1.7 on 2025-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0005_product_received_quantity_alter_product_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_received',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='salesagent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.FloatField(default=10),
        ),
    ]
